# Generated by Django 5.1.3 on 2024-12-27 10:52

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acad', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='payment',
            name='pay_date',
            field=models.DateField(validators=[django.core.validators.MaxValueValidator(datetime.date(2024, 12, 27))]),
        ),
    ]
