# Generated by Django 5.1.3 on 2024-12-28 00:28

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acad', '0002_alter_payment_amount_alter_payment_pay_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='pay_date',
            field=models.DateField(validators=[django.core.validators.MaxValueValidator(datetime.date(2024, 12, 28))]),
        ),
    ]
