# Generated by Django 5.1.3 on 2024-12-27 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='member',
            options={'verbose_name': '회원', 'verbose_name_plural': '회원들'},
        ),
        migrations.AlterField(
            model_name='member',
            name='age',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='member_attachments/'),
        ),
        migrations.AlterField(
            model_name='member',
            name='phone',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
