# Generated by Django 5.1.3 on 2024-12-27 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0003_user_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='is_academy',
            field=models.BooleanField(default=False),
        ),
    ]
