# Generated by Django 5.1.3 on 2024-12-28 01:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0010_alter_academy_admin'),
        ('member', '0005_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='enrolled_academy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='academy.academy'),
        ),
    ]
