# Generated by Django 5.1.3 on 2024-12-27 10:52

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='description',
        ),
        migrations.AddField(
            model_name='academy',
            name='academy_address',
            field=models.CharField(default='기본 주소', max_length=255),
        ),
        migrations.AddField(
            model_name='academy',
            name='academy_email',
            field=models.EmailField(default='default@example.com', max_length=255),
        ),
        migrations.AddField(
            model_name='academy',
            name='academy_name',
            field=models.CharField(default='Default Academy Name', max_length=255),
        ),
        migrations.AddField(
            model_name='academy',
            name='academy_phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='academy',
            name='admin',
            field=models.OneToOneField(default=None, limit_choices_to={'member_type': 'academy_admin'}, on_delete=django.db.models.deletion.CASCADE, related_name='academy', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='academy',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academies', to='academy.category'),
        ),
        migrations.AlterField(
            model_name='academy',
            name='phone',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='academy',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('suspended', 'Suspended')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterModelTable(
            name='academy',
            table='academy',
        ),
    ]
