# Generated by Django 5.1.3 on 2024-12-27 11:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0006_alter_academy_admin'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='academy',
            name='admin',
            field=models.OneToOneField(blank=True, limit_choices_to={'member_type': 'academy_admin'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='academy', to=settings.AUTH_USER_MODEL),
        ),
    ]
