# Generated by Django 5.1.3 on 2024-12-27 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0007_alter_academy_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academy',
            name='academy_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='academy',
            name='academy_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
