# Generated by Django 5.1.3 on 2024-12-28 03:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0011_student'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
    ]
