# Generated by Django 5.1.3 on 2025-02-06 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0012_delete_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademyData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.CharField(max_length=255)),
                ('problem', models.TextField()),
                ('type', models.CharField(max_length=100)),
                ('passage', models.TextField()),
                ('options', models.TextField()),
                ('answer', models.CharField(max_length=255)),
                ('variation', models.CharField(max_length=100)),
                ('grade', models.CharField(max_length=10)),
                ('year', models.CharField(max_length=4)),
                ('strong', models.CharField(max_length=50)),
                ('number', models.IntegerField()),
                ('unit', models.CharField(max_length=255)),
                ('picture', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'academy_data',
            },
        ),
    ]
