# Generated by Django 5.1.3 on 2025-02-06 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0013_academydata'),
    ]

    operations = [
        migrations.RenameField(
            model_name='academydata',
            old_name='year',
            new_name='연도',
        ),
    ]
