# Generated by Django 5.1.3 on 2025-02-06 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0014_rename_year_academydata_연도'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('색인', models.CharField(max_length=255)),
                ('문제', models.TextField()),
                ('유형', models.CharField(max_length=100)),
                ('지문', models.TextField()),
                ('보기', models.TextField()),
                ('정답', models.CharField(max_length=255)),
                ('변형', models.CharField(max_length=100)),
                ('학년', models.CharField(max_length=10)),
                ('연도', models.CharField(max_length=4)),
                ('강', models.CharField(max_length=50)),
                ('번호', models.IntegerField()),
                ('단원', models.CharField(max_length=255)),
                ('그림', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'question_data',
            },
        ),
        migrations.DeleteModel(
            name='AcademyData',
        ),
    ]
