# Generated by Django 5.1.3 on 2025-02-06 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0015_questiondata_delete_academydata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questiondata',
            name='강',
            field=models.CharField(db_column='강', max_length=50),
        ),
        migrations.AlterField(
            model_name='questiondata',
            name='그림',
            field=models.CharField(db_column='그림', max_length=255),
        ),
        migrations.AlterField(
            model_name='questiondata',
            name='단원',
            field=models.CharField(db_column='단원', max_length=255),
        ),
        migrations.AlterField(
            model_name='questiondata',
            name='문제',
            field=models.TextField(db_column='문제'),
        ),
        migrations.AlterField(
            model_name='questiondata',
            name='번호',
            field=models.IntegerField(db_column='번호'),
        ),
        migrations.AlterField(
            model_name='questiondata',
            name='변형',
            field=models.CharField(db_column='변형', max_length=100),
        ),
        migrations.AlterField(
            model_name='questiondata',
            name='보기',
            field=models.TextField(db_column='보기'),
        ),
        migrations.AlterField(
            model_name='questiondata',
            name='색인',
            field=models.CharField(db_column='색인', max_length=255),
        ),
        migrations.AlterField(
            model_name='questiondata',
            name='연도',
            field=models.CharField(db_column='연도', max_length=4),
        ),
        migrations.AlterField(
            model_name='questiondata',
            name='유형',
            field=models.CharField(db_column='유형', max_length=100),
        ),
        migrations.AlterField(
            model_name='questiondata',
            name='정답',
            field=models.CharField(db_column='정답', max_length=255),
        ),
        migrations.AlterField(
            model_name='questiondata',
            name='지문',
            field=models.TextField(db_column='지문'),
        ),
        migrations.AlterField(
            model_name='questiondata',
            name='학년',
            field=models.CharField(db_column='학년', max_length=10),
        ),
    ]
