# Generated by Django 5.1.3 on 2025-02-06 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0016_alter_questiondata_강_alter_questiondata_그림_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='questiondata',
            options={'managed': False},
        ),
    ]
